### ISSUE TITLE
`KeyError` when serializing storage types with fields starting with underscore 

### ISSUE THREAD

**Issue by tomsib2001** [dipdup-io/dipdup#439]
**Steps to reproduce:**
run dipdup with the configuration files (some of them are generated by factori) attached.

**What did you expect to happen:**
DipDup should index operations happening for contract KT1KVfQzyjxoKx2WjcVAatknW3YsR37cCA6s on mainnet

**What actually happened:**
There was a crash
### Environment

* **Python version:**
3.10
* **DipDup version or commit hash:**
5.2.5
* **Database engine version:**
3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1

* **Hasura version:**
* **Are you in docker?**
* no
* **Can you reproduce this issue on `master`?**

```
DEBUG    dipdup.http          Calling `https://api.tzkt.io/v1/operations/transactions?target.in=KT1KVfQzyjxoKx2WjcVAatknW3YsR37cCA6s&offset.cr=0&limit=1000&level.ge=1&level.le=2590307&select=type,id,level,timestamp,hash,counter,sender,nonce,target,initiator,amount,storage,status,hasInternals,diffs,delegate,parameter,hasInternals&status=applied`
DEBUG    dipdup.tzkt          Got 154
DEBUG    dipdup.index         Extracted 1 subgroups (1 operations, 0 filtered by 14 entrypoints and 1 addresses)
INFO     dipdup.index         arago_operations: Processing operations of level 1890783
DEBUG    dipdup.index         arago_operations: Processing 1 operation subgroups of level 1890783
INFO     dipdup.index         arago_operations: onstNXXASgPeKkq11FwbjDgb9ne1BGqoman5deLXhL2SemUn1bL: `on_arago_mint_tokens` handler matched!
DEBUG    dipdup.index         arago_state: Processing big map diffs of level 1890619
INFO     dipdup.index         arago_state: 1890619: `on_arago_untransferable_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_operators_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_metadata_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_meta_token_supply_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_meta_token_info_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_managed_updates` handler matched!
INFO     dipdup.index         arago_state: 1890619: `on_arago_ledger_updates` handler matched!
DEBUG    dipdup.http          Closing gateway session (https://api.tzkt.io)
Traceback (most recent call last):
  File "/home/droserasprout/git/dipdup/.venv/bin/dipdup", line 5, in <module>
    cli()
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 1157, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 1160, in _main
    return await main(*args, **kwargs)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 1076, in main
    rv = await self.invoke(ctx)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 1687, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 1434, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/droserasprout/git/dipdup/.venv/lib/python3.10/site-packages/asyncclick/core.py", line 780, in invoke
    rv = await rv
  File "/home/droserasprout/git/dipdup/src/dipdup/cli.py", line 93, in wrapper
    await fn(*args, **kwargs)
  File "/home/droserasprout/git/dipdup/src/dipdup/cli.py", line 244, in run
    await dipdup.run()
  File "/home/droserasprout/git/dipdup/src/dipdup/dipdup.py", line 393, in run
    await gather(*tasks)
  File "/home/droserasprout/git/dipdup/src/dipdup/dipdup.py", line 103, in run
    indexes_processed = await gather(*tasks)
  File "/home/droserasprout/git/dipdup/src/dipdup/index.py", line 232, in process
    await self._synchronize(sync_level)
  File "/home/droserasprout/git/dipdup/src/dipdup/index.py", line 371, in _synchronize
    await self._process_level_operations(operation_subgroups, sync_level)
  File "/home/droserasprout/git/dipdup/src/dipdup/index.py", line 391, in _process_level_operations
    matched_handlers += await self._match_operation_subgroup(operation_subgroup)
  File "/home/droserasprout/git/dipdup/src/dipdup/index.py", line 474, in _match_operation_subgroup
    args = await self._prepare_handler_args(handler_config, matched_operations)
  File "/home/droserasprout/git/dipdup/src/dipdup/index.py", line 511, in _prepare_handler_args
    storage = deserialize_storage(operation_data, storage_type)
  File "/home/droserasprout/git/dipdup/src/dipdup/datasources/tzkt/models.py", line 189, in deserialize_storage
    operation_data.storage = _process_storage(
  File "/home/droserasprout/git/dipdup/src/dipdup/datasources/tzkt/models.py", line 173, in _process_storage
    value_type = get_dict_value_type(storage_type, key)
  File "/home/droserasprout/git/dipdup/src/dipdup/datasources/tzkt/models.py", line 96, in get_dict_value_type
    raise KeyError(f'Field `{key}` not found in {dict_type}')
KeyError: "Field `_META_TOKEN_SHIFT` not found in <class 'factori_dipdup.types.arago.storage.AragoStorage'>"
```

**Comment by droserasprout** [comment]
Waiting for a fix in TzKT.

**Comment by tomsib2001** [comment]
I keep adding a bug report as a zip file but it seems it does not appear
[bug_report.zip](https://github.com/dipdup-net/dipdup-py/files/9253220/bug_report.zip)
.

**Comment by droserasprout** [comment]
Workaround:

```python
class AragoStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    META_TOKEN_SHIFT: str = Field(..., alias="_META_TOKEN_SHIFT")
    NB_TOKENS_PER_META: str = Field(..., alias="_NB_TOKENS_PER_META")
```

**Comment by arrijabba** [comment]
> Workaround:
> 
> ```python
> class AragoStorage(BaseModel):
>     class Config:
>         extra = Extra.forbid
> 
>     META_TOKEN_SHIFT: str = Field(..., alias="_META_TOKEN_SHIFT")
>     NB_TOKENS_PER_META: str = Field(..., alias="_NB_TOKENS_PER_META")
> ```

Thank you for this! It works great. I have some underscores in storage and parameters and this was driving me nuts lol.

**Comment by droserasprout** [comment]
Fixed in one of the recent datamodel-codegen releases.
