### ISSUE TITLE
DEX demo does not work out of the box

### ISSUE THREAD

**Issue by aguillon** [dipdup-io/dipdup#966]
**Steps to reproduce:**
I copied the `demo_dex` example, created a local environment and followed the [installation steps](https://dipdup.io/docs/getting-started/installation) with `pdm`:

```shell
$ pdm venv create
$ pdm add "dipdup>=7,<8" --venv
(...)
$ source .venv/bin/activate  # manual activation because I was in a pyenv, but let's check that I have everything:
$ which dipdup
/home/arthur/Python/demo_dex/.venv/bin/dipdup
$ pwd
/home/arthur/Python/demo_dex
$ dipdup --version
dipdup, version 7.5.1
$ python3 --version
Python 3.11.8
```
Then in the same directory:
```shell
$ dipdup run
```

**What did you expect to happen:**
I was expecting dipdup to complete its index and maybe create a SQLite database somewhere (or I would have ran it again with a SQLite configuration file)

**What actually happened:**

```
$ dipdup run
INFO     dipdup.dipdup        Setting up database
WARNING  dipdup.database      Using in-memory database; data will be lost on exit
INFO     dipdup.datasources   tzkt_mainnet: hosted (mainnet), protocol v18 (Proxford…TcZDuH)
INFO     dipdup.dipdup        Initializing database schema
INFO     dipdup.datasources   tzkt_mainnet: Fetching latest block
INFO     dipdup.scheduler     Starting job scheduler
INFO     dipdup.dipdup        Waiting for indexes to synchronize before spawning datasources
INFO     dipdup.dipdup        Starting index dispatcher
INFO     dipdup.dipdup        0 contracts fetched from database
INFO     dipdup.dipdup        2 indexes found in database
INFO     dipdup.index         kusd_mainnet: Index is behind the datasource level, syncing: 0 -> 5283778
INFO     dipdup.index         kusd_mainnet: Synchronizing index to level 5283778
INFO     dipdup.index         kusd_mainnet: Status updated: IndexStatus.new -> IndexStatus.syncing
INFO     dipdup.index         hdao_mainnet: Index is behind the datasource level, syncing: 0 -> 5283778
INFO     dipdup.index         hdao_mainnet: Synchronizing index to level 5283778
INFO     dipdup.index         hdao_mainnet: Status updated: IndexStatus.new -> IndexStatus.syncing
INFO     dipdup.index         kusd_mainnet: Fetching operations from level 1 to 5283778
INFO     dipdup.fetcher       Fetching originations from 1 addresses and 0 code hashes
INFO     dipdup.index         hdao_mainnet: Fetching operations from level 1 to 5283778
INFO     dipdup.fetcher       Fetching originations from 1 addresses and 0 code hashes
Traceback (most recent call last):
  File "/home/arthur/Python/demo_dex/.venv/bin/dipdup", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 1205, in __call__
    return anyio.run(self._main, main, args, kwargs, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 73, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2001, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.pyenv/versions/3.11.8/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1989, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 1208, in _main
    return await main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 1120, in main
    rv = await self.invoke(ctx)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 1739, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 1485, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/asyncclick/core.py", line 824, in invoke
    rv = await rv
         ^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/cli.py", line 127, in wrapper
    raise e
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/cli.py", line 120, in wrapper
    await fn(ctx, *args, **kwargs)
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/cli.py", line 289, in run
    await dipdup.run()
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/dipdup.py", line 666, in run
    await gather(*tasks)
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/dipdup.py", line 147, in run
    indexes_processed = any(await gather(*tasks))
                            ^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/index.py", line 221, in process
    await self._synchronize(sync_level)
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/indexes/tezos_tzkt_operations/index.py", line 248, in _synchronize
    await self._process_level_operations(operation_subgroups, sync_level)
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/indexes/tezos_tzkt_operations/index.py", line 275, in _process_level_operations
    subgroup_handlers = match_operation_subgroup(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/indexes/tezos_tzkt_operations/matcher.py", line 225, in match_operation_subgroup
    args = prepare_operation_handler_args(package, handler_config, matched_operations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Python/demo_dex/.venv/lib/python3.11/site-packages/dipdup/indexes/tezos_tzkt_operations/matcher.py", line 54, in prepare_operation_handler_args
    for pattern_config, operation_data in zip(handler_config.pattern, matched_operations, strict=True):
ValueError: zip() argument 2 is shorter than argument 1
________________________________________________________________________________

An unexpected error has occurred! Most likely it's a framework bug.

Please, tell us about it: https://github.com/dipdup-io/dipdup/issues
```

### Environment

* **Python version:** Python 3.11.8
* **DipDup version or commit hash:**  7.5.1
* **Database engine version:**  Note sure if applicable, but 3.44.2 2023-11-24 11:41:44 ebead0e7230cd33bcec9f95d2183069565b9e709bf745c9b5db65cc0cbf92c0f (64-bit)
* **Hasura version:**  N/A
* **Are you in docker?** No
* **Can you reproduce this issue on `next`?** 
Yep

Config and models.py are the same as the demo.

**Comment by aguillon** [comment]
Thank you!
